[advisories]
ignore = ["RUSTSEC-2024-0320"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-3.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "GPL-3.0",
]
confidence-threshold = 1.0
